name: fsc
channels:
- defaults
dependencies:
- cycler=0.10.0=py36_0
- dbus=1.10.20=0
- decorator=4.0.11=py36_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.7.0=np113py36_0
- hdf5=1.8.17=2
- icu=54.1=0
- jbig=2.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- llvmlite=0.19.0=py36_0
- matplotlib=2.0.2=np113py36_0
- mkl=2017.0.3=0
- networkx=1.11=py36_0
- numba=0.34.0=np113py36_0
- numpy=1.13.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2l=0
- pcre=8.39=1
- pillow=4.2.1=py36_0
- pip=9.0.1=py36_1
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np113py36_0
- qt=5.6.2=4
- readline=6.2=2
- scikit-image=0.13.0=np113py36_0
- scipy=0.19.1=np113py36_0
- setuptools=27.2.0=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - mrcfile==1.0.0
  - scikit-learn==0.18.2
  - click==6.7
prefix: /home/cnegro/anaconda3/envs/fsc

